# Generated by Django 6.0.3 on 2026-05-25 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0002_ternal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='header',
            field=models.ImageField(blank=True, null=True, upload_to='headers/'),
        ),
    ]
