# Generated by Django 6.0.3 on 2026-05-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0003_user_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
