# Generated by Django 6.0.3 on 2026-05-26 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0004_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='ternal',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
