# Generated by Django 6.0.3 on 2026-05-27 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0005_delete_person_ternal_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ternal',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
