# Generated by Django 6.0.3 on 2026-05-30 00:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0006_remove_ternal_name_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ternal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
