# Generated by Django 6.0.3 on 2026-05-31 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0007_ternal_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ternal',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
