# Generated by Django 6.0.3 on 2026-06-03 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0008_ternal_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.CharField(choices=[('all', 'いろんなの'), ('diary', '日記'), ('volunteer', 'ボランティア'), ('research', '研究'), ('study', '勉強'), ('company', '企業'), ('work', '仕事'), ('hobby', '趣味')], default='all', max_length=20),
        ),
    ]
