# Generated by Django 6.0.3 on 2026-06-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0009_user_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ternal',
            name='bio',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
